### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by alnfedorov** [gymreklab/chips#53]
Hello!

I was searching for a tool to simulate ChIP-seq experiments targeting histone modifications and found this repository with accompanying preprint. The results are conviencieble, great work. 

Question: Is v2.0 is ready to use, or should I wait for more stable release? 
(Under construction note in the README)

Thanks.

P.S. By the way, v2.0 doesn't compile because of the missing random header in several files.

**Comment by Pandaman-Ryan** [comment]
Hi, 

Thank you for your message and sorry for the late reply.

We have just merged our project into bioconda and now you may download ChIPs using "conda install chips". Anaconda will take care of all the libraries and dependencies for you.
