### ISSUE TITLE
Conda installation fails

### ISSUE THREAD

**Issue by ivargr** [gymreklab/chips#67]
Hi!

Trying to install chips using conda I get this:

```
Could not solve for environment specs
Encountered problems while solving:
  - package chips-2.4-h00214ad_2 requires htslib >=1.14,<1.15.0a0, but none of the providers can be installed
```

The command I ran (also verified that this fails on a github action on a fresh system):

```
conda create --name chips -c bioconda chips`
```

I see that the latest conda version of chips is 2.4, and that my conda tries to install the h00214ad_2 which requires old htslib which does not exist. I also see there's another file with version 2.4 at https://anaconda.org/bioconda/chips/files that is updated to use newer htslib (pushed 3 days agon). However I'm not sure how to specify that file (since that one is also version 2.4, so specifying chips=2.4 does not help).

Am I doing something wrong here, or is there a problem with the conda installation?

**Comment by Pandaman-Ryan** [comment]
Hi @ivargr 

Thank you for reporting this issue. This may have resulted from a recent htslib update. We will update our copy on bioconda as soon as possible. Meanwhile, you can still download and install `chips` from Github or from source files (https://github.com/gymreklab/chips#1-download). Please let me know if these methods don't work for you.

Cheers,
-A
